import { Geist, Geist_Mono } from "next/font/google";
import "@/style/globals.css";
import vazirfont from "@/constants/LocalFont";
import Header from "@/ui/Header";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "context/AuthContext";
import ReactQueryProvider from "./providers/ReactQueryProvider";

export const metadata = {
  title: {
    template: "%s| بلاگ اپ",
    default: "بلاگ اپ",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirfont.variable}  min-h-screen font-sans`}>
        <ReactQueryProvider>
          <AuthProvider>
            <Toaster />

            <div className="container xl:max-w-screen-xl">{children}</div>
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
